# ==========================================
# 数据存储模块配置
# ==========================================

# 1. 监听来自 C++ 行情网关的 UDP 广播
listen:
  port: 9999
  buffer_size: 10485760  # 10MB 接收缓冲

# 2. ClickHouse (冷数据/历史存储)
clickhouse:
  url: "jdbc:clickhouse://127.0.0.1:8123/speed_trader"
  user: "default"
  password: ""
  batch_size: 5000       # 批量写入阈值 (条)
  flush_interval_ms: 1000 # 强制刷盘间隔 (毫秒)

# 3. Redis (热数据/实时查询)
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  pool_max_total: 50
  pool_max_idle: 10